# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.network "private_network", ip: "192.168.44.20"

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = [File.expand_path('../cookbooks', __FILE__)]
    chef.add_recipe "apt-mirror"
    chef.add_recipe "db"
    chef.json = {}
  end
end
